---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  vagrantfile_erb: .kitchen.Vagrantfile.erb
  plugins:
    cachier:
      cache:
        scope: ":box"
        auto_detect: false
        enable:
          #- chef
          - yum
        generic_buckets:
          - ['chef', '/var/chef/cache']
          # Defined only for testing
          - ['wget', '/var/chef/wget']

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer
      file_cache_path: '/var/chef/cache/'

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[boilerplate::default]
    attributes:
